from .domain import (
    Size,
    SizeWithUnit,
    TextElement,
    Video,
    VideoSource,
    VideoSourceType,
    RgbColor,
    Color,
    ThemeColorType,
    SolidFill,
    ShapeBackgroundFill,
    OutlineFill,
    Weight,
    Outline,
    DashStyle,
    ShadowTransform,
    BlurRadius,
    Shadow,
    ShadowType,
    RectanglePosition,
    ShapeProperties,
    CropProperties,
    ColorStop,
    RecolorName,
    Recolor,
    ImageProperties,
    PropertyState,
    StretchedPictureFill,
    PageBackgroundFill,
    PageProperties,
)
from .presentation import Presentation
from .slide import Slide
from .credentials import initialize_credentials
